name: marinette
description: A mobile app for beauty recommendations based on facial features analysis.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  get: ^4.6.5
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image Processing & ML
  google_mlkit_face_detection: ^0.12.0
  camera: ^0.11.0+2
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Audio
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  shared_preferences: ^2.2.2
  
  # Utils
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  intl: ^0.19.0
  share_plus: ^7.2.1

  awesome_notifications: ^0.8.3
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/i18n/
    - assets/i18n/en.json
    - assets/i18n/uk.json
    - assets/audio/
    - assets/audio/nana.mp3
    
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic